[project]
authors = ["Simon Poltier <simon.poltier@mirai-solutions.com>"]
channels = ["conda-forge"]
name = "pixi-localpath-crossplatform"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
