[project]
authors = ["Simon Poltier <simon.poltier@mirai-solutions.com>"]
channels = [
    "conda-forge",
    "file://C:/tmp/custom_artifacts/conda",
    "file:///tmp/custom_artifacts/conda",
]
name = "pixi-localpath-crossplatform"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.main.target.win-64.dependencies]
hll = { version = "*", channel = "file://C:/tmp/custom_artifacts/conda" }
# [feature.main.target.linux-64.dependencies]
# hll = { version = "*", channel = "file:///tmp/custom_artifacts/conda" }


[environments]
default = { features = ["main"] }
